services:
  postgres:
    image: postgres:16
    container_name: financial_postgres
    restart: always
    environment:
      POSTGRES_USER: marreco
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: poupadb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: financial_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: 1234
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
